### ISSUE TITLE
How did you get a grey background?

### ISSUE THREAD

**Issue by TheJimFactor** [jpetitcolas/webgl-experiments#1]
Just wanted to say thanks for your tutorials. I was following along with https://www.jonathan-petitcolas.com/2015/07/27/importing-blender-modelized-mesh-in-threejs.html but I don't know how you got  your grey background. Mine is pure black, though I can see my model rotating.

**Comment by honzik1** [comment]
I guess it is done by css in html

```
<head>
    <title>Rotating mesh - WebGL experiment</title>
    <style>
        body {
            background: #aaa;
            overflow: hidden;
        }
    </style>
</head>
```

**Comment by jpetitcolas** [comment]
I confirm: that's pure CSS. :)
